name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - test  # Change this to the branch you want to deploy from

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16  # You can change this to your desired Node.js version

      - name: Install dependencies
        working-directory: ./web-app
        run: npm install

      - name: Build the app
        working-directory: ./web-app
        run: npm run build

      - name: Deploy to GitHub Pages
        working-directory: ./web-app
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@users.noreply.github.com"
          git checkout master  # Change to your main branch name
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push --force --quiet "https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" master:gh-pages

